# See config.example.yml for documentation.
object: orig/SJBE52/sys/main.dol
hash: b9555f814313209ec258a3f60dd6274fdec11e6b
symbols: config/SJBE52/symbols.txt
splits: config/SJBE52/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
